# Generated by Django 2.1.1 on 2018-09-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='date',
            new_name='timestamp',
        ),
    ]
